# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cumxAw3rM4rWPfSkyEjm4y8mOqZdErnt
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import missingno as msno
!pip install category_encoders
import sys
if 'google.colab' in sys.modules:
    !pip install -q dtreeviz
import dtreeviz
import seaborn as sns
sns.set(
    { "figure.figsize": (6, 4) },
    style='ticks',
    color_codes=True,
    font_scale=0.8
)
# %config InlineBackend.figure_format = 'retina'
import warnings
warnings.filterwarnings('ignore')
sns.set_style('ticks')
from google.colab import drive
drive.mount('/content/drive')

from sklearn.metrics import PredictionErrorDisplay, balanced_accuracy_score, confusion_matrix, ConfusionMatrixDisplay,mean_absolute_error
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, MinMaxScaler, FunctionTransformer, OrdinalEncoder, StandardScaler
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV, KFold, cross_validate
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor, export_text
from sklearn.neighbors import KNeighborsRegressor, KNeighborsClassifier
from sklearn.linear_model import LinearRegression
from sklearn.compose import ColumnTransformer
from category_encoders import TargetEncoder
from sklearn.impute import KNNImputer
from sklearn.pipeline import Pipeline
from sklearn import set_config
set_config(transform_output='pandas')

# Read the CSV file into a DataFrame named AT
AT = pd.read_csv('/content/drive/MyDrive/adverts.csv')

# Display the first few rows of the DataFrame
display(AT.head())

AT_copy = AT.copy()  # create a deep copy of AT

AT_demo = AT.copy()

# Get the number of rows and columns
num_rows, num_cols = AT.shape

print(f"Number of rows: {num_rows}")
print(f"Number of columns: {num_cols}")

AT.describe().T

"""## Visualize Data"""

# Price distribution
sns.histplot(AT['price'], kde=True)
plt.title("Original Price Distribution")
plt.show()

print("Original Skew:", AT['price'].skew())

"""Since data is skewed lets use log transform on AT_demo and plot."""

AT_demo['price_log'] = np.log1p(AT['price'])

sns.histplot(AT_demo['price_log'], kde=True)
plt.title("Log-Transformed Price Distribution")
plt.show()

print("Transformed Skew:", AT_demo['price_log'].skew())

# Mileage distribution
plt.figure(figsize=(10,5))
sns.histplot(AT['mileage'], bins=100, kde=True)
plt.title('Mileage Distribution')
plt.xlim(0, 200000)
plt.show()

# Price by vehicle_condition
plt.figure(figsize=(6,4))
sns.boxplot(x='vehicle_condition', y='price', data=AT)
plt.ylim(0, 200000)
plt.title('Price vs Vehicle Condition')
plt.show()

# Price by fuel_type
plt.figure(figsize=(8,5))
sns.boxplot(x='body_type', y='price', data=AT)
plt.ylim(0, 200000)
plt.xticks(rotation=45)
plt.title('Price vs Fuel Type')
plt.show()

# Top 20 models by median price
top_models = AT.groupby('standard_model')['price'].median().sort_values(ascending=False).head(20)
plt.figure(figsize=(12,5))
sns.barplot(x=top_models.index, y=top_models.values)
plt.xticks(rotation=90)
plt.title('Top 20 Models by Median Price')
plt.show()

sns.scatterplot(x='mileage', y='price',hue='vehicle_condition', data=AT, alpha=0.5)
plt.xlim(0, 200000)
plt.ylim(0, 200000)
plt.title('Price vs Mileage')
plt.show()

sns.scatterplot(x='mileage', y='price',hue='fuel_type', data=AT, alpha=0.5, palette='Paired')
plt.xlim(0, 200000)
plt.ylim(0, 200000)
plt.title('Price vs Mileage')
plt.show()

sns.scatterplot(x='year_of_registration', y='price', data=AT, alpha=0.3)
plt.title('Price vs year_of_registration')
plt.show()

plt.figure(figsize=(10, 8))
sns.heatmap(AT_demo[['mileage', 'year_of_registration', 'price_log']].corr(),square=True, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Heatmap of Numerical Features')
plt.show()

"""## Visualize Missing Values"""

# Check for null values
print("Null values per column:")
display(AT.isnull().sum())

AT.isnull().sum().plot(kind='bar')
plt.title('Missing Values Bar Chart')
plt.ylabel('Missing Values Count')
plt.show()

"""## Fill Missing Values & Deal with Outliers

### Missing Values For year_of_registration

Group by using standard model to fill missing values
"""

AT_copy['year_of_registration'] = AT_copy['year_of_registration'].fillna(
    AT_copy.groupby('standard_model')['year_of_registration'].transform('median')
)

AT_copy['year_of_registration'] = AT_copy['year_of_registration'].fillna(
    AT_copy.groupby('standard_make')['year_of_registration'].transform('median')
)

AT_copy['year_of_registration'] = AT_copy['year_of_registration'].fillna(
    AT['year_of_registration'].median()
)

"""### Outliers"""

temp_years_imputation = (
    AT_copy.groupby(['standard_model','standard_colour','standard_make','body_type'])['year_of_registration']
    .transform('median')
)

mask = AT_copy['year_of_registration'] < 1903
AT_copy.loc[mask, 'year_of_registration'] = temp_years_imputation[mask]

AT_copy['year_of_registration'].min()

"""### Missing Values For mileage"""

AT_copy['mileage'] = AT_copy['mileage'].fillna(
    AT_copy.groupby(['standard_model', 'standard_make'])['mileage']
    .transform('median')
)

"""### Missing Values For standard_colour"""

AT_copy['standard_colour'] = AT_copy['standard_colour'].fillna(
    AT_copy.groupby(['standard_model', 'standard_make'])['standard_colour']
    .transform(lambda x: x.mode()[0] if not x.mode().empty else np.nan)
)

global_mode = AT_copy['standard_colour'].mode()[0]
AT_copy['standard_colour'] = AT_copy['standard_colour'].fillna(
    AT_copy.groupby('standard_make')['standard_colour']
    .transform(lambda x: x.mode()[0] if not x.mode().empty else global_mode)
)

"""### Missing Values For body_type"""

AT_copy['body_type'] = AT_copy['body_type'].fillna(
    AT_copy.groupby(['standard_model', 'standard_make'])['body_type']
    .transform(lambda x: x.mode()[0] if not x.mode().empty else np.nan)
)

global_mode = AT_copy['body_type'].mode()[0]
AT_copy['body_type'] = AT_copy['body_type'].fillna(
    AT_copy.groupby('standard_make')['body_type']
    .transform(lambda x: x.mode()[0] if not x.mode().empty else global_mode)
)

"""### Missing Values For fuel_type"""

AT_copy['fuel_type'] = AT_copy['fuel_type'].fillna(
    AT_copy.groupby(['standard_model', 'standard_make'])['fuel_type']
    .transform(lambda x: x.mode()[0] if not x.mode().empty else np.nan)
)

global_mode = AT_copy['fuel_type'].mode()[0]
AT_copy['fuel_type'] = AT_copy['fuel_type'].fillna(
    AT_copy.groupby('standard_make')['fuel_type']
    .transform(lambda x: x.mode()[0] if not x.mode().empty else global_mode)
)

AT_copy.isnull().sum()

display(AT_copy.head())

"""### Dataset and Groups of Feature & Split

Lets use the normalized data as our target
"""

target = 'price'
low_card_cat_feat = ['body_type','fuel_type',]
binary_cat_feat = ['vehicle_condition','crossover_car_and_van']
high_card_cat_feat = ['standard_make', 'standard_model','standard_colour']
num_feat = ['mileage','year_of_registration']

X=AT_copy[low_card_cat_feat + high_card_cat_feat + num_feat + binary_cat_feat ]
y = AT_copy[target]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

y_train_log = np.log1p(y_train)
y_test_log  = np.log1p(y_test)

num_pipe = Pipeline(steps=[
    ('scaler', StandardScaler())  # numeric features passed as-is
])
# Categorical pipeline: impute missing values, then one-hot encode
low_card_cat_pipe = Pipeline(steps=[
    ('onehot', OneHotEncoder(sparse_output=False,
    handle_unknown='infrequent_if_exist',  # groups rare categories
    drop='if_binary')),
])

high_card_cat_pipe = Pipeline(steps=[
     ('tar_enc', TargetEncoder())
])
binary_pipe = Pipeline(steps=[
    ('ordinal_enc', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1))
])

preprocessor = ColumnTransformer([
    ('num', num_pipe, num_feat),
    ('low_cat', low_card_cat_pipe, low_card_cat_feat),
    ('binary', binary_pipe, binary_cat_feat),
    ('high_cat', high_card_cat_pipe, high_card_cat_feat)
])

"""### Decision Tree Regressor"""

dtr = DecisionTreeRegressor(
    max_depth=12,          # control complexity
    random_state=42,
    min_samples_leaf=10
)

clf_pipe = Pipeline([
    ('preprocess', preprocessor),
    ('tree_reg', dtr)
])

clf_pipe.fit(X_train, y_train_log)

importances = clf_pipe.named_steps['tree_reg'].feature_importances_
feature_names = clf_pipe.named_steps['preprocess'].get_feature_names_out()
feat_ = pd.DataFrame({
    'feature': feature_names,
    'importance': importances
}).sort_values('importance', ascending=False)

sns.barplot(
    data=feat_.head(10),
    x='importance',
    y='feature'
)
plt.title('Top 10 Feature Importances')
plt.show()

train_score = clf_pipe.score(X_train, y_train_log)
test_score  = clf_pipe.score(X_test, y_test_log)

print("Train R²:", train_score)
print("Test R²:", test_score)

log_test = clf_pipe.predict(X_test)

"""reverse the order for log transformed price to its orignal scale"""

y_pred = np.expm1(log_test)
y_test_actual = np.expm1(y_test_log)

"""### Mean absolute score"""

mean_absolute_error(y_test_actual, y_pred)

y_pred_baseline = y_test_actual.mean()

y_pred_baseline

np.mean(np.abs((y_test_actual - y_pred_baseline)))

"""### Cross validation score"""

scores_dict = cross_validate(clf_pipe, X_train, y_train_log, cv=5, return_train_score=True)
scores = pd.DataFrame(scores_dict)
print(scores['train_score'].mean(), scores['train_score'].std())
print(scores['test_score'].mean(), scores['test_score'].std())

"""### Grid Search"""

param_grid = {
    'tree_reg__max_depth': [ 1, 3, 4, 8, 10, 12],
    'tree_reg__min_samples_leaf': [ 10, 20, 30 ]
}

from sklearn.model_selection import ParameterGrid
list(ParameterGrid(param_grid))

gs = GridSearchCV(clf_pipe, param_grid, return_train_score=True)

gs_results = gs.fit(X_train, y_train_log)

gs_df = pd.DataFrame(gs_results.cv_results_)

gs_df.head(5)

gs_df_sh = gs_df[ [
    'param_tree_reg__max_depth', 'param_tree_reg__min_samples_leaf',
    'mean_train_score', 'std_train_score',
    'mean_test_score', 'std_test_score', 'rank_test_score'
] ].sort_values('rank_test_score')
gs_df_sh

gs_results.best_params_

"""### Linear Regression"""

LR = LinearRegression()

clf_pipe = Pipeline([
    ('preprocess', preprocessor),
    ('linear_reg', LR)
])

clf_pipe.fit(X_train, y_train_log)

train_score = clf_pipe.score(X_train, y_train_log)
test_score  = clf_pipe.score(X_test, y_test_log)

print("Train R²:", train_score)
print("Test R²:", test_score)

"""### Actual vs Predicted"""

PredictionErrorDisplay.from_estimator(
    clf_pipe, X_test, y_test_log, kind="actual_vs_predicted", scatter_kwargs=dict(alpha=0.5)
);

PredictionErrorDisplay.from_estimator(
    clf_pipe, X_test, y_test_log, kind="residual_vs_predicted", scatter_kwargs=dict(alpha=0.5)
);

log_test = clf_pipe.predict(X_test)

y_pred = np.expm1(log_test)
y_test_actual = np.expm1(y_test_log)

residuals = y_test_actual - y_pred

sns.histplot(residuals);

"""### Cross Validated Score"""

scores_dict = cross_validate(clf_pipe, X_train, y_train_log, cv=5, return_train_score=True)
scores = pd.DataFrame(scores_dict)
print(scores['train_score'].mean(), scores['train_score'].std())
print(scores['test_score'].mean(), scores['test_score'].std())

"""### KNN Regression"""

knnr = KNeighborsRegressor(n_neighbors=11)

clf_pipe = Pipeline([
    ('preprocess', preprocessor),
    ('knn_reg', knnr)
])

clf_pipe.fit(X_train, y_train_log)

train_score = clf_pipe.score(X_train, y_train_log)
test_score  = clf_pipe.score(X_test, y_test_log)

print("Train R²:", train_score)
print("Test R²:", test_score)

"""### Actual vs Predicted"""

PredictionErrorDisplay.from_estimator(
    clf_pipe, X_test, y_test_log, kind="actual_vs_predicted", scatter_kwargs=dict(alpha=0.5)
);

PredictionErrorDisplay.from_estimator(
    clf_pipe, X_test, y_test_log, kind="residual_vs_predicted", scatter_kwargs=dict(alpha=0.5)
);

log_test = clf_pipe.predict(X_test)

y_pred = np.expm1(log_test)
y_test_actual = np.expm1(y_test_log)

residuals = y_test_actual - y_pred

sns.histplot(residuals);

"""### Cross Validated Score"""

scores_dict = cross_validate(clf_pipe, X_train, y_train_log, cv=5, return_train_score=True)
scores = pd.DataFrame(scores_dict)
print(scores['train_score'].mean(), scores['train_score'].std())
print(scores['test_score'].mean(), scores['test_score'].std())
